stages:
  - containerization
  - deployment

image: moreillon/ci-dind
services:
  - name: docker:19.03.12-dind


variables:
  APPLICATION_NAME: shisakoshou
  CONTAINER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE::${CI_COMMIT_SHORT_SHA}
  K8S_INGRESS_HOST: shisakoshou.home.maximemoreillon.com

containerization:
  stage: containerization
  tags:
    - dind
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deployment:
  stage: deployment
  tags:
    - dind
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
